### ISSUE TITLE
didReceiveIncomingPushWithPayload is not called when app is killed

### ISSUE THREAD

**Issue by hhlingRoomie** [ConnectyCube/connectycube-ios-sdk-releases#4]
I am facing an issue where I am not able to receive any VOIP push notification if the app is in killed state. I was testing on iOS 13.2 and iOS 13.1 device. No issue if the app is in the foreground and in the background mode. Even when i test with the connectycube sample app, I face the same issue also.

Appreciate if your team could help me on this. Thanks

**Comment by DaveLomber** [comment]
Could you pleaese check the capabilities you set in Xcode

Especially, what Background Modes you set

It should be Voice over IP check box set

Like here
https://www.raywenderlich.com/5817-background-modes-tutorial-getting-started

Please double check
