### ISSUE TITLE
Demo Crashing

### ISSUE THREAD

**Issue by Nishant9SPL** [ConnectyCube/connectycube-ios-sdk-releases#6]
After recreated the pod file and tried to install all the libraries. When tried to run the app, then it gave me the error related to "PINRemoteImage" library.

So, changed the version from "#pod 'PINRemoteImage', '~> 2.1.4'"  to "pod 'PINRemoteImage', '~> 3.0.3'"

After that, it gave error in file: UIImageVIew + UserImage.swift

if let image = PINRemoteImageManager.shared().cache.object(forKey: key) as? UIImage {

PINRemoteImageManager.shared().cache.setObject(placehodler, forKey: key)

So, After changed the above 2 lines with below:

if let image = PINRemoteImageManager.shared().cache.objectFromDisk(forKey: key) as? UIImage {

PINRemoteImageManager.shared().cache.setObjectOnDisk(placehodler, forKey: key)

After above changes, the app build succeeded. But when run the app, it is directly crashing. (crash is in the PINCache pod file).

Can you please let me know about the above? OR share the demo which can be run directly and can be checked?

Thank you.

**Comment by Nishant9SPL** [comment]
After installing the cocoapod library, it gives below errors:


Incompatible block pointer types initializing '__strong PINDiskCacheObjectBlock' (aka 'void (^__strong)(PINDiskCache * _Nonnull __strong, NSString * _Nonnull __strong, id<NSCoding>  _Nullable __strong)') with an expression of type 'void (^)(PINDiskCache *__strong, NSString *__strong, __strong id<NSCoding>, NSURL *__strong)'

Incompatible block pointer types sending 'void (^)(PINDiskCache *__strong, NSString *__strong, __strong id<NSCoding>, NSURL *__strong)' to parameter of type 'PINDiskCacheObjectBlock _Nullable' (aka 'void (^)(PINDiskCache * _Nonnull __strong, NSString * _Nonnull __strong, id<NSCoding>  _Nullable __strong)')


**Both errors are of Library named "PINRemoteImage".**

Currently, as per the given demo, its version is "2.1.4".   (pod 'PINRemoteImage', '~> 2.1.4')

So, I have updated version to below:
pod 'PINRemoteImage', '~> 3.0.1'

After updating version, it is giving error in file: **UIImageView+UserImage.swift**

1) Value of type 'PINRemoteImageCaching' has no member 'object'
2) Value of type 'PINRemoteImageCaching' has no member 'setObject'


Can you please check with give library version and the code is updated with the specific version and let us know.

**Comment by DaveLomber** [comment]
@Nishant9SPL please share your pod file

also, are you integrating the lib into your own app or code sample?

**Comment by Nishant9SPL** [comment]
@DaveLomber Belos is my pod file.

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat
  pod 'ConnectyCube', '~> 1.7'
  pod 'YapDatabase', '~> 3.1.2'
  pod 'SVProgressHUD', '~> 2.2.5'
  #pod 'PINRemoteImage', '~> 2.1.4'
  pod 'PINRemoteImage', '~> 3.0.1'
  pod 'LetterAvatarKit', '~> 1.1.7'
  pod 'SlackTextViewController', '~> 1.9.6'
  pod 'StaticDataTableViewController', '~> 2.5.0'
  pod 'Reusable', '~> 4.0.5'
  pod 'SwiftDate', '~> 5.1.0'
  pod 'SwiftMessages', '5.0.1'
  pod 'BadgeSwift', '~> 7.0.0'
  pod 'SwiftySound', '~> 1.0.0'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'Lightbox', '~> 2.1.2'
  pod 'WSTagsField', '~> 4.1.0'

  target 'ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Issue with IBDesignable: https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098
  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end

end


**Please note that, 'PINRemoteImage', '~> 2.1.4' was creating an issue in function. So, I have updated its version.**


As of now, I am checking with given code sample only. Still didn't integrated into my own app.

**Comment by DaveLomber** [comment]
Hi @Nishant9SPL 
I was able to successfully run the demo w/o any changes (`pod 'PINRemoteImage', '~> 2.1.4'`)

<img width="171" alt="Screenshot 2020-11-16 at 11 09 59" src="https://user-images.githubusercontent.com/39332586/99233837-6f734800-27fc-11eb-903f-a3d0acd1e54c.png">

Please let me know what was your original error with PINRemoteImage

I used Xcode 12.1 and iPhone 11 (iOS 14.1) simulator

**Comment by Nishant9SPL** [comment]
@DaveLomber Thanks for the update.

For your reference:
After installing the POD libraries, I was getting below error of "PINRemoteImage":

Incompatible block pointer types initializing '__strong PINDiskCacheObjectBlock' (aka 'void (^__strong)(PINDiskCache * _Nonnull __strong, NSString * _Nonnull __strong, id _Nullable __strong)') with an expression of type 'void (^)(PINDiskCache *__strong, NSString *__strong, __strong id, NSURL *__strong)'

Incompatible block pointer types sending 'void (^)(PINDiskCache *__strong, NSString *__strong, __strong id, NSURL *__strong)' to parameter of type 'PINDiskCacheObjectBlock _Nullable' (aka 'void (^)(PINDiskCache * _Nonnull __strong, NSString * _Nonnull __strong, id _Nullable __strong)')


So, I have updated that library's newer version: pod 'PINRemoteImage', '~> 3.0.1' and update below method for new version.
UIImageView+UserImage.swift
PINRemoteImageManager.shared().cache.objectFromDisk(forKey: key) as? UIImage


Then I was able to build the code successfully.

For your note, I am using Xcode 11.5 and cocoapod version 1.9.3

Thank you.

**Comment by DaveLomber** [comment]
@Nishant9SPL  great it finally works well !
Thank you for notifying us
